### ISSUE TITLE
window.location.href = URL.createObjectURL(blob)

### ISSUE THREAD

**Issue by guest271314** [mdn/create-media-stream-destination#1]
`Blob` lifetime is tied to original `document`, `URL.createObjectURL(blob)` logs `404` error. Added `<audio>` element to set `.src` property to `Blob URL` at https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createMediaStreamDestination.

**Comment by chrisdavidmills** [comment]
I like your fix - makes much more sense than the original demo. I've implemented it in the live demo.

Thanks!
